version: '3.8'

services:
  app:
    build: ./app
    volumes:
      - ./app:/app
      - /app/node_modules
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 20s node index.js
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: people_db
    ports:
      - "3000:3000"
    restart: always
    networks:
      - fullcycle-net
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - fullcycle-net
    depends_on:
      - app

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    command: --innodb-use-native-aio=0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: people_db
    tty: true
    restart: always
    networks:
      - fullcycle-net
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  fullcycle-net:

volumes:
  mysql-data:
